os: linux
dist: focal
language: rust
rust:
- 1.79.0
services:
- docker
cache:
  cargo: true
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh -i id_rsa $DEPLOY_USER@$DEPLOY_SERVER "docker run hello-world" || travis_terminate 1
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
env:
  global:
  - CARGO_BUILD_JOBS=2
script:
- cargo build --workspace
after_success:
- export VERSION=$(git rev-parse --short HEAD)
- rsync -rave "ssh -i id_rsa" --exclude=target --exclude=.cargo . $DEPLOY_USER@$DEPLOY_SERVER:~/axum-backend
- ssh -i id_rsa $DEPLOY_USER@$DEPLOY_SERVER "
    set -e
    mkdir -p ~/axum-backend
    cd ~/axum-backend
    export VERSION='$VERSION'
    
    # Build and push web-server image
    docker build --build-arg VERSION=$VERSION --target web-server -t bloomingflower/axum-backend-web:$VERSION .
    docker tag bloomingflower/axum-backend-web:$VERSION bloomingflower/axum-backend-web:latest
    docker push bloomingflower/axum-backend-web:$VERSION
    docker push bloomingflower/axum-backend-web:latest
    
    # Build and push sse-server image
    docker build --build-arg VERSION=$VERSION --target sse-server -t bloomingflower/axum-backend-sse:$VERSION .
    docker tag bloomingflower/axum-backend-sse:$VERSION bloomingflower/axum-backend-sse:latest
    docker push bloomingflower/axum-backend-sse:$VERSION
    docker push bloomingflower/axum-backend-sse:latest
    
    # Clean up Docker resources
    docker system prune -af --volumes
"

branches:
  only:
  - master
jobs:
  fast_finish: true