[package]
name = "rust_endpoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Tokio is an asynchronous runtime for Rust
tokio = { version = "1.37.0", features = ["full"] }
# Axum is a web framework based on hyper, the Rust HTTP library
axum = { version = "0.7.5", features = ["macros"] }
# HTTP testing utilities for Axum applications
httpc-test = "0.1.9"
# Serde is a serialization/deserialization library for Rust
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.80"
# Tower is a library of modular and reusable components for building robust networking clients and servers
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["fs"] }
tower-cookies = "0.10.0"
hyper = "1.3.1"

[dev-dependencies]
# Anyhow is a Rust library for Error type that can represent any error
anyhow = "1"