version: '3.8'
services:
  postgres:
    image: postgres:16.3
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: