version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "bullseye"
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

  pg:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    restart: always