# Cargo config file.
# See https://doc.rust-lang.org/cargo/reference/config.html

# Environment variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="axum_backend=debug"

# Service Environment variables.
# IMPORTANT: These are only used for the `cargo run` command.
# For deoployed environments, should be managed by container orchestration.

## Secrets
# Keys and passwords below are for local development only.
# i.e., Encryption not required.

SERVICE_DB_URL = "postgres://dev_app:dev_app@localhost/dev_app"


## ConfigMap

# This will be relative to Cargo.toml file.
# In deployed environments, this use absolute path.
SERVICE_WEB_FOLDER="web-folder/"