[package]
name = "scylla-test"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]

[lints]
workspace = true
