on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    # Add a step to run the server before tests
    - name: Start Server
      run: cargo run &
    # Ensure the server has time to start up
    - name: Wait for Server
      run: sleep 5
    # Finally, run tests
    - name: Run tests
      run: cargo test --verbose
