name: Rust CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'Makefile'
      - '.travis.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'Makefile'
      - '.travis.yml'
      - 'Dockerfile'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.80.0, stable]
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: dev
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      # Ensure the DB has time to start up
      - name: Wait for DB
        run: sleep 50
      # Add a step to run the server before tests
      - name: Start Server
        run: cargo run -p web-server &
      # Ensure the server has time to start up
      - name: Wait for Server
        run: sleep 5
      # Finally, run tests
      - name: Run tests
        run: cargo run -p web-server --example test
        #cargo test --verbose

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: |
  #           bloomingflower/axum-backend-web:latest
  #           bloomingflower/axum-backend-sse:latest