name: Rust CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "Makefile"
      - ".travis.yml"
      - "Dockerfile"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "Makefile"
      - ".travis.yml"
      - "Dockerfile"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.80.0, stable]
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: dev
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      kafka:
        image: wurstmeister/kafka:2.13-2.8.1
        env:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
          - 9092:9092
      zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181
      scylla:
        image: scylladb/scylla:5.2.0
        ports:
          - 9042:9042

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Check Rust version
        run: rustc --version
      - name: Build
        run: cargo build --verbose
      - name: Wait for services
        run: |
          sleep 30
          nc -z localhost 9092 || (echo "Kafka is not running" && exit 1)
          nc -z localhost 9042 || (echo "Scylla is not running" && exit 1)
      - name: Start Server
        run: cargo run -p web-server &
      - name: Wait for Server and Health Check
        run: |
          sleep 10
          for i in {1..30}; do
            if curl -sSf http://localhost:3000/health > /dev/null 2>&1; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server... (attempt $i)"
            sleep 2
          done
      - name: Run tests
        run: cargo run -p web-server --example test
        #cargo test --verbose

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            bloomingflower/axum-backend-web:latest
          target: web-server
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push SSE Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            bloomingflower/axum-backend-sse:latest
          target: sse-server
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache